import test from 'node:test';import assert from 'node:assert/strict';import {parseEther} from 'ethers';import {createProject} from '../project.mjs';
test('Crowdfunding success and refund paths',async t=>{const p=await createProject();t.after(()=>p.chain.close());
 await t.test('zero contribution rejected',()=>assert.rejects(()=>p.contract.contribute.staticCall({value:0}),/Zero/));
 await t.test('successful funding aggregates contributors',async()=>{await p.action({action:'contribute',account:1,amount:'0.5'});await p.action({action:'contribute',account:2,amount:'0.5'});assert.equal(await p.contract.raised(),parseEther('1'))});
 await t.test('claim before deadline rejected',()=>assert.rejects(()=>p.contract.claim.staticCall(),/settled/));
 await t.test('refund before deadline rejected',()=>assert.rejects(()=>p.contract.connect(p.chain.signers[1]).refund.staticCall(),/unavailable/));
 await t.test('contribution at deadline rejected',async()=>{const deadline=Number(await p.contract.deadline());await p.chain.rpc.request({method:'evm_mine',params:[{timestamp:deadline}]});assert.equal(await p.chain.timestamp(),deadline);await assert.rejects(()=>p.contract.contribute.staticCall({value:1}),/ended/)});
 await t.test('non-owner claim rejected',()=>assert.rejects(()=>p.contract.connect(p.chain.signers[1]).claim.staticCall(),/Owner/));
 await t.test('successful campaign has no refund',()=>assert.rejects(()=>p.contract.connect(p.chain.signers[1]).refund.staticCall(),/unavailable/));
 await t.test('owner claim empties the contract',async()=>{await p.action({action:'claim'});assert.equal(await p.chain.balance(await p.contract.getAddress()),0n);assert.equal(await p.contract.claimed(),true)});
 await t.test('double claim rejected',()=>assert.rejects(()=>p.contract.claim.staticCall(),/Already/));
 await t.test('failed campaign rejects owner claim',async()=>{await p.action({action:'reset',goal:'2'});await p.action({action:'contribute',account:1,amount:'0.5'});await p.action({action:'contribute',account:2,amount:'0.25'});await p.action({action:'advance'});await assert.rejects(()=>p.contract.claim.staticCall(),/settled/)});
 await t.test('refunds are isolated by supporter',async()=>{await p.action({action:'refund',account:1});assert.equal(await p.contract.contributions(p.chain.addresses[1]),0n);assert.equal(await p.contract.contributions(p.chain.addresses[2]),parseEther('0.25'));assert.equal(await p.chain.balance(await p.contract.getAddress()),parseEther('0.25'))});
 await t.test('double refund rejected',()=>assert.rejects(()=>p.contract.connect(p.chain.signers[1]).refund.staticCall(),/Nothing/));
 await t.test('second supporter gets their refund',async()=>{await p.action({action:'refund',account:2});assert.equal(await p.chain.balance(await p.contract.getAddress()),0n)});
});
